### ISSUE TITLE
Invalid schema path in error object

### ISSUE THREAD

**Issue by ikokostya** [geraintluff/tv4#117]
test.js:
```javascript
var tv4 = require('tv4');

var schema = {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "oneOf": [
        {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                }
            },
            "required": ["data"]
        },
        {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object"
                }
            },
            "required": ["error"]
        }
    ]
};

var data = {};

var isValid = tv4.validate(data, schema);
if (!isValid) {
    console.log(tv4.error);
}
```

Output:
```
[kostya@arch tv4-test]$ npm ls
/home/kostya/proj/tv4-test
└── tv4@1.0.16

[kostya@arch tv4-test]$ node -v
v0.10.26
[kostya@arch tv4-test]$ node test.js 
{ message: 'Data does not match any schemas from "oneOf"',
  code: 11,
  dataPath: '',
  schemaPath: '/oneOf',
  subErrors: 
   [ { message: 'Missing required property: data',
       code: 302,
       dataPath: '',
       schemaPath: '/oneOf/0/oneOf/0/required/0',
       subErrors: null,
       stack: 'Error: Missing required property: data\n    at new ValidationError (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:1133:12)\n    at ValidatorContext.createError (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:156:9)\n    at ValidatorContext.validateObjectRequiredProperties (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:721:22)\n    at ValidatorContext.validateObject (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:688:11)\n    at ValidatorContext.validateAll (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:394:11)\n    at ValidatorContext.validateOneOf (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:915:20)\n    at ValidatorContext.validateCombinations (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:819:11)\n    at ValidatorContext.validateAll (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:395:11)\n    at Object.api.validate (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:1233:24)\n    at Object.<anonymous> (/home/kostya/proj/tv4-test/test.js:29:19)' },
     { message: 'Missing required property: error',
       code: 302,
       dataPath: '',
       schemaPath: '/oneOf/1/oneOf/1/required/0',
       subErrors: null,
       stack: 'Error: Missing required property: error\n    at new ValidationError (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:1133:12)\n    at ValidatorContext.createError (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:156:9)\n    at ValidatorContext.validateObjectRequiredProperties (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:721:22)\n    at ValidatorContext.validateObject (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:688:11)\n    at ValidatorContext.validateAll (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:394:11)\n    at ValidatorContext.validateOneOf (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:915:20)\n    at ValidatorContext.validateCombinations (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:819:11)\n    at ValidatorContext.validateAll (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:395:11)\n    at Object.api.validate (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:1233:24)\n    at Object.<anonymous> (/home/kostya/proj/tv4-test/test.js:29:19)' } ],
  stack: 'Error: Data does not match any schemas from "oneOf"\n    at new ValidationError (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:1133:12)\n    at ValidatorContext.createError (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:156:9)\n    at ValidatorContext.validateOneOf (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:946:15)\n    at ValidatorContext.validateCombinations (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:819:11)\n    at ValidatorContext.validateAll (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:395:11)\n    at Object.api.validate (/home/kostya/proj/tv4-test/node_modules/tv4/tv4.js:1233:24)\n    at Object.<anonymous> (/home/kostya/proj/tv4-test/test.js:29:19)\n    at Module._compile (module.js:456:26)\n    at Object.Module._extensions..js (module.js:474:10)\n    at Module.load (module.js:356:32)' }
```

Expected schema path in sub error is `/oneOf/0/required/0`.

**Comment by mitar** [comment]
Was this fixed?

**Comment by chaimleib** [comment]
I think so. My fix and test was merged in, it looks like @geraintluff just forgot to close this issue. G, if you're reading this, could you close the issue?
