### ISSUE TITLE
Errors when validating a document which is itself a json schema

### ISSUE THREAD

**Issue by abraae** [geraintluff/tv4#198]
This is slight convoluted, but I need to validate a json document which is itself a json schema.

I am therefore validating it using tv4 against the json schema meta-schema as found at http://json-schema.org/documentation.html.

My document is as follows:

    {
        "$schema": "http://json-schema.org/draft-04/schema",
        "type": "object",
        "properties": {
            "favoriteColor": {
                "type": "string"
            }
        }
    }

The schema I am validating against is http://json-schema.org/schema.

I get the following error:

    { errors: 
       [ { [ValidationError: Invalid type: string (expected array)]
           message: 'Invalid type: string (expected array)',
           params: [Object],
           code: 0,
           dataPath: '/type',
           schemaPath: '/properties/type/anyOf/1/type',
           subErrors: null,
           stack: 'Error: Invalid type: string (expected array)\n    at new ValidationError (/usr/lib/node_modules/tv4/tv4.js:1428:12)\n    at ValidatorContext.createError (/usr/lib/node_modules/tv4/tv4.js:365:9)\n    at ValidatorContext.validateType (/usr/lib/node_modules/tv4/tv4.js:755:14)\n    at ValidatorContext.validateBasic (/usr/lib/node_modules/tv4/tv4.js:725:19)\n    at ValidatorContext.validateAll (/usr/lib/node_modules/tv4/tv4.js:603:19)\n    at ValidatorContext.validateAnyOf (/usr/lib/node_modules/tv4/tv4.js:1116:20)\n    at ValidatorContext.validateCombinations (/usr/lib/node_modules/tv4/tv4.js:1076:11)\n    at ValidatorContext.validateAll (/usr/lib/node_modules/tv4/tv4.js:608:11)\n    at ValidatorContext.validateObjectProperties (/usr/lib/node_modules/tv4/tv4.js:996:21)\n    at ValidatorContext.validateObject (/usr/lib/node_modules/tv4/tv4.js:947:11)' } ],
    missing: 
       [ 'http://json-schema.org/draft-04/schema',
     'http://json-schema.org/draft-04/schema': 'http://json-schema.org/draft-04/schema' ],
      valid: false }

I can prevent these errors by editing the meta schema and:

a) removing the line:

    "id": "http://json-schema.org/draft-04/schema#",

b) changing the definition of "type" from:

        "type": {
            "anyOf": [
                { "$ref": "#/definitions/simpleTypes" },
                {
                    "type": "array",
                    "items": { "$ref": "#/definitions/simpleTypes" },
                    "minItems": 1,
                    "uniqueItems": true
                }
            ]
        },

to...

        "type": {
            "anyOf": [
                { "$ref": "#/definitions/simpleTypes" }
            ]
        },

I don't really feel I should need to edit the metaschema like this - am I doing something wrong?

**Comment by nine99systems** [comment]
Hi,
I am facing similar issue but in my case I am validating JSON against a schema but calling method : v4.validateMultiple(objData, schema);  and it gives error : ValidationError: Invalid type: array (expected object).
Any one can help me?
